seeditsolution/cprogram

- Sum of two number
Sum of two numbers in c programming
> Sum of two number

- Greaterbhai
Programe to find greatest of two number
> Greater bhai

- swap two numbers without third variable
Swap two numbers without third variable
> swap two numbers

- Selection Sort Program in
In Selection sort, the smallest element is exchanged with the first element of the unsorted list of elements (the exchanged element takes the place where smallest element is initially placed). Then the second smallest element is exchanged with the second element of the unsorted list of elements and so on until all the elements are sorted. In the following C program we have implemented the same logic.
> Selection Sort Program in

- Greater number
Program to find greater of two number
> Greater number

- fibonaci of certain number
> Create fibonaci of certain number

- gretest
Program to find the greatest of two number
> greatest number

- Linked List traversal
Here I have coded How to traverse a singly linked list, and also how to display using pointer concepts.
> Linked list traversal

- Diamond_pattern
Program to Print diamond pattern using for loop
> Diamond_pattern

- Program to Check Prime Number
Program to Check Prime Number with C language
> Program to Check Prime Number

- evenodd
> to check for even odd number

- armstrongnum
C program to check Armstrong Number in C
> Armstrong Num

- assemblyprog
Simple assembly program code to add two numbers in c program
> Assembly program in C

- primenumber
Program to Print Prime Numbers between 1 to 100 using For Loop
> Creation of Prime Numbers

- Conversion_program
A menu-driven program conversion where many cases are there where input is taken from the user and the amount is converted and the result is printed
> Menu_driven_program

- calculate power Optimized
Calculates Power of number in log n time complexity.
> Power Calculation

- OddEven
In this programme you can check that given number is even or not
> OddEvenNumberCheck

- Product
> Product method

- Fibonacci series
Program to find Fibonacci series in c
> Fibonacci series

- factorial number
program to find factorial of any number
> factorial number

- pyramid of *
program to make  Full Pyramid of *
> pyramid of *

- prime no between to intervals
This is a programme to find prime no b/w two numbers.
> prime no between to intervals

- prime number
check whether given number is prime number or not
> find the whether the number is prime or not

- Greaternumber
Program to find greatest number among two numbers
> Greaternumber

- pryamid using *
Program to print Pyramid Pattern
> pyramid using star

- Find even and odd number
C Program for finding even and odd number
> Find even and odd number

- Prime Number in C
Program to find Prime Number in C programming
> Create Prime Number in C

- Multiple if statements
We can use multiple if statements to check more than one conditions
> Multiple if statements

- palindrome
C Program to Check if a Given String is Palindrome
> Palindrome

- sum of two integer
C program of printing sum of two integer
> Create sum of two integer

- Program to convert binary to decimal.c
Hey sir please accept my pull request
> Create Program to convert binary to decimal.c

- print n natural numbers
Program to print natural numbers from 1 to n.
> print n natural numbers

- Swapping Two Numbers
Create program for swapping variable without using third variable
> Create Swapping Two Numbers

- CODE FOR BANK APPLICATION:
A sample C programming code for real time Bank application program is given below. This program will perform all below operations.
1.Creating new account – To create a new account
2.Cash Deposit – To Deposit some amount in newly created account
3.Cash withdrawal – To Withdraw some amount from your account
4.Display Account information – It will display all informations of the existing accounts
Log out
5.Clearing the output screen and display available options
> Create CODE FOR BANK APPLICATION:

- Factorial Program
> Factorial Program

- threegreternumber
progrmme to find three greter numbers
> greternumbers

- Greaterno
program to find the greatest of two numbers
> Greaterno.

- pelindromeno
to find whether any number is palindrome or not in c
> palindromeno

- GREATER NO.
> Create GREATER NO.

- Palindrome no.
Program to find Palindrome numbers in a given range.
> Palindrome no.

- Structures as Function Arguments
Structures as Function Arguments
You can pass a structure as a function argument in the same way as you pass any other variable or pointer.
> Structures as Function Arguments

- PrimeNumber
How to find prime number in number system.
> PrimeNumber

- Indian Flag
Sir kuch accha banaya hai kafi mehenat lagi please accept pull request.Lets make India Proud.
> Create Indian Flag

- greatertwonumber
program to find the greater of two number in c.
> greatertwonumber

- Addition Number
> Addition Number

- c program of array
> array implementation in c

- printing pattern
big fan sir plz accept pull request
> Created a c program of printing pattern

- reverse_digits
this program in c language reverse the digits of a number
> reverse the digits of a number

- Tac Toe game
> Tic_Tac_Toe

- How to Reverse a String using C programming Language
A Simple Program to Find Reverse String in C Language.
> ReverseString

- Merge two arrays
> Merge two arrays

- swapping of two numbers
Program to swap two numbers using third variable in C.
> swapping of two numbers.

- Find missing number
> Missing number

- PascalTriangle.cpp
it will print the Pascal combination of triangle
> PascalTrinagle

- Armstrong Number
How to find armstrong number using c
> Armstrong Number

- finding the largest element in an array
Source code for finding the largest element in an array
> Create finding the largest element in an array

- program to print integer
>  print integer

- mergetwosortedarrays
Program to merge two sorted arrays into one single array.
> merge_two_sorted_arrays

- greaternumber
C Program to Find the Biggest of 3 Numbers
> grester number 3

- c program to find duplicate character in a given string
In this program I have used very simple idea to find duplicate characters in a string in C Language
>  find the duplicate characters in a given string

- int, float, double and char
C Program to Find the Size of int, float, double and char
> C Program to Find the Size of int, float, double and char

- calculate the salary
program to calculate the salary as per the following table:
_________________________
Gender   |   Years of Service   |   Qualification      |   Salary.     | 
_________________________
Male     |     >=10             |      Post-Graduate   |    15000.     |
|     >=10             |      Graduate        |    10000      |
|     <10              |      Post-Graduate   |    10000.     |
|     <10              |      Graduate        |    7000.      |
----------------------------------------------------------------------
Female   |     >=10             |      Post-Graduate   |    12000.     |
|     >=10             |      Graduate        |    9000.      |
|     <10              |      Post-Graduate   |    10000.     |
|     <10              |      Graduate        |    6000.      |
> Create calculate the salary

- factorial.c
C program to find factorial of number
> factorial.c

- basicgameinc
A basic roll game in C Language
> basicgameinc

- findingtickets
this is basically finding the number of tickets need for particular seats in bus or train.
> Finding number of tickets required .

- compond_interest
this c program allows user to calculate compoud interest for his or her investments
> calculate compound interest

- Merge two sorted arrays
An easier approach to merge two sorted arrays would be by traversing both the arrays to keep track of current element in both the arrays, finding the least value among the two and updating the final array with the least value
> Merge two sorted arrays

- check whether a no. is prime or not
Creating a c program for checking a no. is a prime one or not
> Program for checking a no. is prime or not

- Convert binary to decimal
Create program to convert binary to decimal in C language.
> Program to convert binary to decimal

- HangmangameinC
This is a traditional hangman game in which you have to guess a word letter by letter. For this to work you need to create a text file with name "words.txt" in same directory of this program and add some words in it and each word separated by ' | ' symbol.
> HangmangameinC.c

- palindromecheck
This program is strictly written in C language to check whether a given number is palindrome or not.
> Palindromenumbercheck

- pascaltriangle
C program to print Pascal's triangle by taking input from user.
> pascaltriangle

- Count largest elements in Array
Program to count the largest element in array-hackerRank solution for Birthday Cake Candles
> Count largest elements in Array

- Covert degree celsius into fahrenheit
Source code in c language for converting degree celsius  into fahrenheit
> Create Covert degree celsius into fahrenheit

- addoftwono
> addoftwono

- Convert Numbers to Roman Numerals
1. Take a decimal number as input.
2. Check if the number is greater than 1000 or 900 or 500 or 400 or 100 or 90 or 50 or 40 or 10 or 9 or 5 or 4 or 1.
3. If it is, then store its equivalent roman number in a array.
4. Repeat the step 2-3 with the left over number.
> Convert Numbers to Roman Numerals

- greatearno
> greatearno

- armstrongC
program to check whether a number is armstrong or not in C language.
> armstronginC

- Product of two No.
Program for Multiply two Numbers
> Product of two No.

- multiplyoftwono
program of multiplication of two number
> multiplyoftwono

- program to check leap year
This a source code of finding a leap year in c language.
> Checking leap year

- gassbooking
program to create a project of gassbooking system for user choice.
> gassbooking project

- BestTimeToBuyStocks.cpp
Say you have an array for which the ith element is the price of a given stock on day i.
If you were only permitted to complete at most one transaction (i.e., buy one and sell one share of the stock), design an algorithm to find the maximum profit.
Note that you cannot sell a stock before you buy one.
>  BestTimeToBuyStocks.cpp

- reverse number
C Program to Reverse an Integer
> reverse number

- square of a number
> Create square of a number

- Print numbers
> Print numbers

- use of bitwise operators
Program to use of bitwise operators
> use of bitwise operators

- Star_pattern_heart
> Star_pattern_heart

- LargestNo.
This will take input of 3 nos and will give output as the largest no. among them.
> Largest no.

- Linked_List_in_C
Menu Driven Program to show implementation of linked list in C
> Linked List in C: Menu Driven Program

- simple interest finder.c
This is a basic SI finder in C program for Beginners
> Create simple interest finder.c

- Music Player
Music Player Using C++ Programming Language
> Music Player

- prime number
C Program to Check Whether a Number is Prime or Not
> prime number

- leapyear.c
> create leapyear in c

- Factorial of any number
Easiest way to calculate of any number
> Factorial of any number

- check to prime no or not
> check to prime no or not

- SquareFill with stars
This is the square full fill with
*
> Create SquareFill with stars

- SumOfTwoNumber
C program to find the sum of two number
> sumoftwonum

- greater_two_number
largest of two number use C Programming
> greater_two_number

- multiplication of 2 matrix
Propose multiplication of two matrix
> Create multiplication of 2 matrix

- reverse number
to reverse a number in c prograam
> revere number

- Leap year
> C Program:- Leap Year

- passing address
> passing address

- print rainbow
_i am very excited becauce i sucessfull print rainbow. thanku._
> simple print rainbow using c program

- greatestoftwonumbers
To find greatest of two numbers using C program
> greatestoftwonumbersprogram

- add two numbers in c
created a new file for adding two numbers in C Programming
> adding two numbers in c

- NUmber to Words conversation
this is very efficient and helpful program to convert number in to word by me
> Create NUmber to Words conversation

- Duplicate number
find the duplicate number in c language.
> duplicate number in c

- Print Upper case Lower case alphabet
It can print Upper case as well as lower case alphabets
> Create Print Upper case Lower case alphabet

- cieser-cipher-encryption
It is an implementation of ceaser cipher algorithm for encryption and decryption.
> cieser-cipher

- Triplet of three numbers (a,b,c)
Input : Triplet of three numbers (a,b,c)
Output : 1 if they are either in strictly increasing (a>b>c) or decreasing (a<b<c) order
0, otherwise.
> Triplet of three numbers (a,b,c)

- C Program to Add Two Matrices Using Multi-dimensional Arrays
#include <stdio.h>
int main() {
int r, c, a[100][100], b[100][100], sum[100][100], i, j;
printf("Enter the number of rows (between 1 and 100): ");
scanf("%d", &r);
printf("Enter the number of columns (between 1 and 100): ");
scanf("%d", &c);
printf("\nEnter elements of 1st matrix:\n");
for (i = 0; i < r; ++i)
for (j = 0; j < c; ++j) {
printf("Enter element a%d%d: ", i + 1, j + 1);
scanf("%d", &a[i][j]);
}
printf("Enter elements of 2nd matrix:\n");
for (i = 0; i < r; ++i)
for (j = 0; j < c; ++j) {
printf("Enter element a%d%d: ", i + 1, j + 1);
scanf("%d", &b[i][j]);
}
// adding two matrices
for (i = 0; i < r; ++i)
for (j = 0; j < c; ++j) {
sum[i][j] = a[i][j] + b[i][j];
}
// printing the result
printf("\nSum of two matrices: \n");
for (i = 0; i < r; ++i)
for (j = 0; j < c; ++j) { …
> C Program to Add Two Matrices Using Multi-dimensional Arrays

- TowerOfHanoi
C recursive function to solve tower of hanoi puzzle
> Tower of Hanoi

- Binary Search
C Program to implement binary search
> Binary Search

- Swapping of two number
> Create Swapping of two number

- graphicscarmove
Program to move a car on a console of graphics by c programming with the cleardevice() method.
> graphicscarmove

- Insertion sort
Following C program asks from user to enter array size and array elements to sort that array using insertion sort technique. And finally display the sorted array on the screen.
> Insertion sort C program

- sentence to a file
C Program to Write a Sentence to a File
> Create sentence to a file

- c program to find factorial of a number using recursive function
here we are finding factorial of any integer number using recursive function in c
> factorial using recursive function

- Sort in Descending order
lists the numbers in descending order
> Create Sort in Descending order

- Binary_to_decimal_conversion
This is a C program that converts a binary number into its equivalent decimal form.
> Binary_to_decimal_conversion

- quicksort_c
Program to implement quick sort in c
> quicksort_c

- qcircle.c
Circular Queue Implementation Using C
> Circular Queue Implementation

- add multiply divide and substract
one combine programe of add multiply divide and substrect in c language
> add multiply divide substrect in one programe

- Roots of a Quadratic Equation
The standard form of a quadratic equation is:
ax2 + bx + c = 0, where
a, b and c are real numbers and
a != 0
The term b2-4ac is known as the discriminant of a quadratic equation. It tells the nature of the roots.
If the discriminant is greater than 0, the roots are real and different.
If the discriminant is equal to 0, the roots are real and equal.
If the discriminant is less than 0, the roots are complex and different.
> Program to Find Roots of a Quadratic Equation

- substrect of two integers
programe of substrect of two integer in c language
> substrect of two integers

- Quick Sort
Implementing Quick Sort algorithm
> Quick Sort

- Smallest
program to find smallest of two numbers in c
> Smallest Number

- m%n remainder 1.c
Program to get remainder 1 when N divides M .
When two integers, say M and N are given.
> m%n remainder

- string task
The program was supposed to do the following: in the given string, consisting if uppercase and lowercase Latin letters, it:
deletes all the vowels, inserts a character "." before each consonant,replaces all uppercase consonants with corresponding lowercase ones.
Vowels are letters "A", "O", "Y", "E", "U", "I", and the rest are consonants.
> string task

- triangular patterns
this helps to create a triangular pattern
> triangular patterns

- Fibonachi series
> Create Fibonachi series

- Binary_Search
Program to Search an elements in a given list using Binary Search.
> Binary_Search

- Smaller number
Smaller number in c programming language.
> Smaller number

- Check Armstrong number of n digits
Program to find Armstrong number of n digits
> Create Check Armstrong number of n digits

- reversestr
> reversestr

- Fibonacci Series up to n terms
Program to find fibonacci Series up to n terms
> Fibonacci Series up to n terms

- the hollow square star pattern
it's a star pattern printing program...
> Create the hollow square star pattern

- fibanocci_series
A legend way to calculate fibanoci series
> Fibanocci_series

- Decimal to Binary Number Conversion
Program to convert a Decimal number to its respective binary number
> Decimal to Binary number conversion

- odd number
program to find odd numbers in c
> Odd number

- SimpleCalci
C Program to Make a Simple Calculator Using switch...case
> SimpleCalci

- ArmstrongNumber
> ArmstrongNumber

- countvowels
c program to count vowels in a string
> countvowels

- Creat A Simple Calculator
A calculator for adding , subtracting , multiplication and division
> Creat a calculator

- Addfunction
Program to add two numbers through a function.
> Addfunction

- Biggest of three  number
C program to find the biggest of three numbers
> Biggest of three number

- Electric Bill
C Program to Calculate Electricity Bill
> Electric Bill

- Funnystring
Program to demonstrate the funny string problem in c.
> Funnystring

- print an integer
Basically added a C file to print an integer
> print an integer with C

- Palindrome Number
> Check whether a Number is Palindrome Number or Not

- odd or enen
c program to find even or odd number
> even or odd

- Liquidityno
Programs to find the greatest 5 numbers in c
> Liquidity Ratio Number

- to find armstrong numbers using recursion
this code written in c ,to find armstrong numbers using recursion.
> this code finds armstrong numbers using recursion

- qlinear.c
Linear Queue Implementation Using C
> Linear Queue Implementation

- Hello, World
Write a program to print Hello World
> Hello World

- multiplication of 2.12 and 3.88
programe of multiplication  of 2.12 and 3.88
> multiplication

- Linked List implementation of Queue
Menu-Driven Program implementing all the operations on Linked Queue
> Linked List implementation of Queue

- Convert Binary Number to Decimal Number
This program converts binary number to equivalent decimal number.
> Program to Convert Binary Number to Decimal Number

- Copy String Without Using strcpy()
C Program to Copy String Without Using strcpy()
> Copy String Without Using strcpy()

- C program to insert an element in an array
this a program to insert an element in an array
> Create C program to insert an element in an array

- primefactors
Cpp program to count the prime factors of the number using Sieve of Eratosthenes
> primefactors

- ReverseNumber.c
A c program to reverse an integer.
> ReverseNumber.c

- palindrome using while loop
Program to check whether a number is palindrome or not
> Palindrome n

- Positive or Negative
Program to find Positive or Negative Number using Nested If Condition in C
> Positive or Negative

- sorting of arrays
> Create sorting of arrays

- countingsort
Program to implement counting sort in c.
> countingsort

- Bubble Sort
Bubble Sort is the simplest sorting algorithm that works by repeatedly swapping the adjacent elements if they are in the wrong order. It will show the output like:
Sorted array:
11 12 22 25 34 64 90
> Bubble sort

- concatenate str
Concatenate Two Strings Without Using strcat()
> Create concatenate str

- celsius to fahrenheit
Program to convert temperature from Celsius to Fahrenheit
> Celsius_To_Fahrenheit

- Find odd or even no
Program to find odd or even no
> Create Find odd or even no

- Factorial_of_a_number
This is the a c program to find factorial of a number
> Factorial_of_a_number

- find prime numbers in a given range
Upon execution of below program, the user would be asked to provide the from & to range and then the program would display all the prime numbers in sequential manner for the provided range. Using this program you can find out the prime numbers between 1 to 100, 100 to 999 etc. You just need to input the range, for e.g. if you want the prime numbers from 100 to 999 then enter numbers 100 and 999 when program prompts for input.
> find prime numbers in a given range

- Stock_Span
> Stock_Span

- fibonacci
its a febonacii number programe
Thankyou sir for you support
> febonacii number

- maxinarray
Program to maximum in an array
> maxinarray

- SMALLNO
how to select a very small number (approximately 0) in a C code
> Create  SMALLNO

- ugly numbers
Check whether a given number is an ugly number
> Create ugly numbers

- Sorting Arrays
This program will implement a one-dimensional array of some fixed size, filled with some random numbers, then will sort all the filled elements of the array.
> Sort the Array in an Ascending Order

- Greatest No.
Program to find the greatest no.
> Greater No.

- Simple Interest
> Simple Interest

- fabonaccisequence
Program to display Fabonacci sequence upto n terms in C.
> fabonaccisequence

- greatest number 1
program to find the greatest of two numbers in c
> Create greatest number 1

- selectionsort
Program to implement selection sort in c.
> selectionsort

- even or odd number
C Program to check if number is even or odd.
> even or odd number

- checkPalindrome
check palindrome using while loop
> checkPalindrome

- standard deviation
Program to Calculate Standard Deviation in c
> standard deviation

- to find prime number
> Create to find prime number

- Squareroot
Find the square root of any number ?
> Squareroot

- Remove common alphabets from 2nd string
Removing common alphabets from 2nd string.
> Create Remove common alphabets from 2nd string

- Remove repeated words in string.
Learn Removing repeated elements of array elements
> Create Remove repeated words in string.

- Fibonacci Series in c
Program of Fibonacci series in c language
> Fibonacci Series in c

- Pascal's Triangle
Program to create a Pascal's Triangle
> Pascal's Triangle

- Perfect Number
Program to find a Perfect Number using C.
> Perfect Number

- merge and quick sort
Sorting a list using  merge and quick sort algorithm
> Merge and quick Sort

- smallarge
Program to find Largest and Smallest Element in an Array
> small and great

- factorial_prog
added new c program to find factorial of given number
> factorial_prog

- Radix-Sort
The idea of Radix Sort is to do digit by digit sort starting from least significant digit to most significant digit. Radix sort uses counting sort as a subroutine to sort.
> Radix-Sort

- count_totalno_of_alphabet_digit_and_special_char
program  to count total number of alphabets, digits and special characters in a string.
> count char number and alphabet

- prime_or_not
Program to find whether a number is prime or not.
> primr_or_not

- Display occurrence of word in given string.
Creating to display occurrence of word in given string.
> Create Display occurrence of word in given string.

- Merge sort
> Program for merge sorting by c

- Readability_cs50
Solution for the Harvard cs50 pset2/readability
> Readability_cs50

- Bubble Sort using C
In Bubble sort, Each element of the array is compared with its adjacent element. The algorithm processes the list in passes. A list with n elements requires n-1 passes for sorting. Consider an array A of n elements whose elements are to be sorted by using Bubble sort. The algorithm processes like following.
In Pass 1, A[0] is compared with A[1], A[1] is compared with A[2], A[2] is compared with A[3] and so on. At the end of pass 1, the largest element of the list is placed at the highest index of the list.
In Pass 2, A[0] is compared with A[1], A[1] is compared with A[2] and so on. At the end of Pass 2 the second largest element of the list is placed at the second highest index of the list.
In pass n-1, A[0] is compared with A[1], A[1] is compared with A[2] and so on. At the end of this …
> Bubble Sort using C

- addition and subtraction
> addition and subtraction

- C program for Prime Number
> to check Prime Or Not

- next →← prev Matrix multiplication in C
Matrix multiplication in C: We can add, subtract, multiply and divide 2 matrices. To do so, we are taking input from the user for row number, column number, first matrix elements and second matrix elements. Then we are performing multiplication on the matrices entered by the user.
In matrix multiplication first matrix one row element is multiplied by second matrix all column elements.
Let's try to understand the matrix multiplication of 2*2 and 3*3 matrices by the figure given below:
>  next →← prev Matrix multiplication in C

- Matrix.c
This C program performs matrix multiplication. In matrix multiplication, we take two matrices of order m*n and p*q respectively to find a resultant matrix of the order m*q where n is equal to p . Time Complexity of this algorithm is O(n3).
> created a program two multiply the matrix

- 2D Matrix Multiplication
Program to Multiply 2D matrix in C.
> 2D Matrix Multiplication

- multiple of 3
program to find multiple of 3..
> multiple of 3

- sleep_sort
1) The above algorithm tries to sort it in ascending order. Can you sort an input array in descending order using sleep sort. Think upon it.
2) Is it a comparison based sorting algorithm ? How many comparisons this algorithm makes ?
[ Answer : No, it makes zero comparisons ]
3) Can we do sleeping sort without using windows.h header and without using Sleep() function?
[One idea can be to create a priority queue where the elements are arranged according to the time left before waking up and getting printed. The element at the front of the priority queue will be the first one to get waked up. However the implementation doesn’t looks easy. Think on it.]
Time Complexity
Although there are many conflicting opinions about the time complexity of sleep sort, but we can approximate the time …
> Sleep_sort

- Leap Year Checker
C program to check whether the year is a leap year or not.
> Leap Year Checker

- Half pyramid of *
The program creates a half pyramid of *.
> Create Half pyramid of *

- First small letter in string
Finding the first small letter in string.
> Create First small letter in string

- FahrenheitToCentigrade
Temperature of a city in Fahrenheit degrees is input through the keyboard. Write a program to convert this temperature into Centigrade degrees.
> FahrenheitToCentigrade

- Smart Calculator
> Smart Calculator

- infix to postfix
c program to convert an infix expression in to postfix expression
> infix to postfix

- factorailno
program to find factorial of a number in c
> factorialno

- simple game
> Create simple game

- celcius to farenheit
A C program to convert temperature of celcius to farenheit
> celcius to farenheit

- affinecypher
It is an encryption code (Affine Cypher)
> affinecypher

- greternumber
C Language Program is accept two number from user,check the number and find the gretest number from those two number and display gretest number.
> greternumber

- to find fibonacci series
> Create to find fibonacci series

- Tower of Hanoi
Code of tower of Hanoi in c language.
> Tower of Hanoi in c

- additionoftwonumber
> addingtwonumber

- BFS in Graph
Program run Breadth First Search in Undirected Graph
> Graph - BFS

- Pattern Program in c
> Pattern in C

- reversing of string
> reverse-string

- treetransversal.c
this is code for tree transversal in c
> code for treetransversal in c

- sine_series
C program to find the sine of x using the series :
sin x = x - x3/3! + x5/5! - x7/7! + x9/9! ........
> sine_series

- N reverse natural number
This is a program to print reverse natural numbers
> Create N reverse natural number

- duplicateelementsinarray
c program to find Duplicate element in array
> duplicateelement

- Oil Spill Game. C
> Create Oil Spill Game. C

- Multiplication of Two Numbers
The program gives a basic scenario of how to multiply two numbers
> Multiply Two Numbers

- bubble_sort
> bubble_sort

- Selection sort
Sorting an array using selection sort in C.
> Selection sort

- Convert decimal to binary
This program converts a decimal number into binary.
> Convert decimal to binary

- String reverse
This is a C  language program to reverse the strings
> String reverse

- C Program to Find the Size of int, float, double and char
This C program helps one to find the size of int, float double and char. It takes a variable as input and gives the size of the same.
> Create C Program to Find the Size of int, float, double and char

- no of digits in number
C Program to Count Number of Digits in a Number using While Loop
> Count No's of digit in Number

- mapOfIndia
This program will print the map of India as the output
> Map of India

- Armstrong_ number
Check number is Armstrong or not
> Armstrong_number

- hollow diamond
Here is the program to diamond inscribed inside rectangle .
> Diamond inscribed inside rectangle

- Days Conversion
Added Days Conversion program in C lang
> Created Days Conversion program

- Knapsack problem
> Create Knapsack problem

- optimized implementation of bubble sort
Optimized Implementation of Bubble Sort Program
> bubble sort program

- gretter new
Program to find the greatest of two number in c
> gretter new

- strassen's matrix multiplication
C program to multiply two NxN matrices using Strassen’s Matrix Multiplication method.
> Strassen's Matrix Multiplication

- fibonacci no.
> fibonacci no.

- quickSort
> quicksort program

- Simple calculator
This is a simple calculator program in c for adding/subtracting/multiplying/dividing two numbers
> Create Simple calculator

- Window Sliding Technique
Code of Window Sliding Technique in cpp.
>  Window Sliding Technique

- Hello world Program
Program to Print Hello world in C Language
> Hello World Program

- program to check vowel using switch case
Program to check vowel using switch case
> Check vowel using switch case

- Greater Integer
Find the greatest integer among 2 integer input.
> Greatest Integer

- Program of adding two number in c
Program of adding two number in c
> Adding numbers

- Check Leap Year
> Check Leap Year

- C Program for Rat in a Maze
Efficient C program to clear Backtracking Concepts
> C Program for Rat in a Maze

- greaterno10
C Program is used to find the greatest among ten numbers.
> greaterno10

- addition no
> Addition of 2 no

- multiply two no.
Program to Multiply two numbers in c program.
> multiply  two no.

- Positive Negative Zero
Simple C program to find whether the entered number is Positive Negative or Zero
> Positive Negative Zero

- Snake Game in C
> Snake Game

- Program to multiply two matrices
> multiplication of two matrices

- Program to Reverse a String Using Recursion
Below is a program to reverse a user input string using recursion in C language
> Program to Reverse a String Using Recursion

- stack,c
A topic of data structure based on the rule LIFO . Last in first out
This will help students to understand the concept behind this.
Anyone can easily understand this code because all comments are their and the code is well written
> Created stack using  C programming language

- Floyd warshall algorthim
Floyd warshall algorthim using c
> Create Floyd warshall algorthim

- factorial by recursion
program to find factorial by recursion
> factoralbyrecursion

- Identifies_missing_numbers
This C Program identifies missing numbers in a given array.
Here is source code of the C Program to identify missing numbers in a given array. The C program is successfully compiled and run on a Linux system. The program output is also shown below.
output should be :
Enter size of array : 6
Enter elements into array : 
1
2
3
5
6
Missing element is : 4
> C Program to identify missing Numbers in a given Array

- To Print a Rombus star pattern
In this program we will see how to print a rombus star pattern in c
#include <stdio.h>  
int main()  
{  
int n;  
printf("Enter the number of rows");  
scanf("%d",&n);  
for(int i=n;i>=1;i--)  
{  
for(int j=1;j<=i-1;j++)  
{  
printf(" ");  
}  
for(int k=1;k<=n;k++)  
{  
printf("*");  
}  
printf("\n");  
}  
return 0;  
}
> Create To Print a Rombus star pattern

- graterNumber
> graterNumber

- anke game in c language
hope you like it too litle bit different
> snake game in c

- Star Pattern
> Diamond star pattern

- hangman game
Hangman Game in C is a simple C program which has been designed to demonstrate different application formats and syntaxes of C programming language. The game is very simple to play and the coding has been done such as way that the applicatoin is an interesting and entertaining game. In the game, there is not any use of graphics, user defined function and user defined header file.
> hangman game

- biggernumber
program to find the greatest of two number in c
> biggernumber

- hexadecimaltodecimal
converts hexadecimal to decimal
> hexadecimaltodecimal

- numberSwap
> numberSwap

- example to calculate income tax
An example to calculate income tax
> example to calculate income tax

- algorithm for finding height of a binary tree
given algorithm is a good algorithm for finding the height of a tree
> this is a algorithm for finding the height of a tree
